AtmBankingApi/AtmBanking.UI/Controllers/CustomerInfoController.cs
using AtmBanking.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace AtmBanking.UI.Controllers
{
    public class CustomerInfoController : Controller
    {

        private IConfiguration _configuration;
        public CustomerInfoController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
       
        public async Task<IActionResult> CustomerInfoDetails()
        {
            //StringContent content = new StringContent(JsonConvert.SerializeObject(customerInfo), Encoding.UTF8, "application/json");
            IEnumerable<CustomerInfo> customerinforesult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "CustomerInfo/GetCustomerInfoDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        customerinforesult = JsonConvert.DeserializeObject<IEnumerable<CustomerInfo>>(result);
                    }
                }
            }
            return View(customerinforesult);
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(CustomerInfo customerInfo)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(customerInfo), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "CustomerInfo/Register";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Register successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(CustomerInfo customerInfo)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(customerInfo), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "CustomerInfo/Token";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                        return RedirectToAction("CustomerInfoDetails");
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong credentials!";
                        return View();
                    }
                }
            }
            
        }
    }
}

AtmBankingApi/AtmBanking.UI/Controllers/TransactionDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AtmBanking.Entity.Models;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace AtmBanking.UI.Controllers
{
    public class TransactionDetailsController : Controller
    {
        private IConfiguration _configuration;
        public TransactionDetailsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> TransactionDetails()
        {
            //StringContent content = new StringContent(JsonConvert.SerializeObject(customerInfo), Encoding.UTF8, "application/json");
            IEnumerable<TransactionDetails> transactiondetailsresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "TransactionDetails/GetTransactionDetails";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        transactiondetailsresult = JsonConvert.DeserializeObject<IEnumerable<TransactionDetails>>(result);
                    }
                }
            }
            return View(transactiondetailsresult);
        }
        public IActionResult TransactionDetailsEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> TransactionDetailsEntry(TransactionDetails transactionDetails)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(transactionDetails), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "TransactionDetails/TransactionDetailsEntry";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Transaction Details entered successfully!!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
    }
}

AtmBankingApi/AtmBanking.UI/Views/CustomerInfo/CustomerInfoDetails.cshtml
@model IEnumerable<AtmBanking.Entity.Models.CustomerInfo>
    <div class="row">
        <div class="col-12">
            <h3>CustomerDetails</h3>
            <hr />
            <table class="table table-light table-bordered table-hover">
                <thead>
                    <tr>
                        <th>CustomerId</th>
                        <th>name</th>
                        <th>address</th>
                        <th>city</th>
                        <th>email_address</th>
                        <th>contact_info</th>
                        <th>card_no</th>
                        <th>pin_no</th>
                        <th>account_number</th>
                        <th>account_type</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    
                       
                    <tr>
                        <td>@item.CustomerId</td>
                        <td>@item.name</td>
                        <td>@item.address</td>
                        <td>@item.city</td>
                        <td>@item.email_address</td>
                        <td>@item.contact_info</td>
                        <td>@item.card_no</td>
                        <td>@item.pin_no</td>
                        <td>@item.account_number</td>
                        <td>@item.account_type</td>
                        
                    </tr>
                    }
                </tbody>
            </table>
         
        </div>
    </div>

AtmBankingApi/AtmBanking.UI/Views/CustomerInfo/Login.cshtml
@model AtmBanking.Entity.Models.CustomerInfo

<h2>Login</h2>
<hr />
<form method="post">
    <div class="form-group">
        <label for="Firstname">Email</label>
        <input type="text" class="form-control" asp-for="email_address">
    </div>
    <div class="form-group">
        <label for="Firstname">Password</label>
        <input type="text" class="form-control" asp-for="Password">
    </div>
    <input type="submit" class="btn btn-primary" value="Login">
    <button type="button" class="btn btn-secondary">Reset</button>
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <hr />
    <a asp-controller="CustomerInfo" asp-action="Register">Register</a>
</form>

AtmBankingApi/AtmBanking.UI/Views/CustomerInfo/Register.cshtml
@model AtmBanking.Entity.Models.CustomerInfo


<form method="post" enctype="multipart/form-data">
    <h2>Customer Entry</h2><hr />
    <div class="form-group">
        <label>Name</label>
        <input type="text" asp-for="name" class="form-control" placeholder="Enter name" required />
    </div>
    <div class="form-group">
        <label>Address</label>
        <input type="text" asp-for="address" class="form-control" placeholder="Enter address" required />
    </div>
    <div class="form-group">
        <label>City</label>
        <input type="text" asp-for="city" class="form-control" placeholder="Enter city" required />
    </div>
    <div class="form-group">
        <label>Email-Address</label>
        <input type="text" asp-for="email_address" class="form-control" placeholder="Enter emailaddress" required />
    </div>
    <div class="form-group">
        <label>Contact-Info</label>
        <input type="text" asp-for="contact_info" class="form-control" placeholder="Enter contact-info" required />
    </div>
    <div class="form-group">
        <label>Card Number</label>
        <input type="text" asp-for="card_no" class="form-control" placeholder="Enter  card number" required />
    </div>
    <div class="form-group">
        <label>PinNo</label>
        <input type="text" asp-for="pin_no" class="form-control" placeholder="Enter  pin number" required />
    </div>
    <div class="form-group">
        <label>Account Type</label>
        <input type="text" asp-for="account_type" class="form-control" placeholder="Enter  Account Type" required />
    </div>
    <div class="form-group">
        <label>Account Number</label>
        <input type="text" asp-for="account_number" class="form-control" placeholder="Enter  Account number" required />
    </div>
    <div class="form-group">
        <label>Password</label>
        <input type="text" asp-for="Password" class="form-control" placeholder="Enter password" required />
    </div>
    <input type="submit" value="Save" class="btn btn-outline-success" />
    <input type="button" value="Reset" class="btn btn-outline-secondary" />
    <hr />
    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
    <a asp-controller="CustomerInfo" asp-action="Login">Login</a>
    <br/>
    <a asp-controller="TransactionDetails" asp-action="TransactionDetailsEntry">TransactionDetailsEntry</a>
</form>